"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    let datas = [
      {
        coupon_select: 51,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 1,
        event_id: 1,
      },
      {
        coupon_select: 1,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 1,
        event_id: 2,
      },
      {
        coupon_select: 11,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 1,
        event_id: 3,
      },
      {
        coupon_select: 21,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 1,
        event_id: 4,
      },
      {
        coupon_select: 31,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 1,
        event_id: 5,
      },
      {
        coupon_select: 41,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 1,
        event_id: 6,
      },
      {
        coupon_select: 64,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 1,
        event_id: 7,
      },
      {
        coupon_select: 71,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 1,
        event_id: 8,
      },
      {
        coupon_select: 82,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 1,
        event_id: 9,
      },

      {
        coupon_select: 51,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 2,
        event_id: 1,
      },
      {
        coupon_select: 2,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 2,
        event_id: 2,
      },
      {
        coupon_select: 12,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 2,
        event_id: 3,
      },
      {
        coupon_select: 21,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 2,
        event_id: 4,
      },
      {
        coupon_select: 32,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 2,
        event_id: 5,
      },
      {
        coupon_select: 42,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 2,
        event_id: 6,
      },
      {
        coupon_select: 65,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 2,
        event_id: 7,
      },
      {
        coupon_select: 71,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 2,
        event_id: 8,
      },
      {
        coupon_select: 84,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 2,
        event_id: 9,
      },

      {
        coupon_select: 52,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 3,
        event_id: 1,
      },
      {
        coupon_select: 2,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 3,
        event_id: 2,
      },
      {
        coupon_select: 11,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 3,
        event_id: 3,
      },
      {
        coupon_select: 21,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 3,
        event_id: 4,
      },
      {
        coupon_select: 31,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 3,
        event_id: 5,
      },
      {
        coupon_select: 41,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 3,
        event_id: 6,
      },
      {
        coupon_select: 65,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 3,
        event_id: 7,
      },
      {
        coupon_select: 71,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 3,
        event_id: 8,
      },
      {
        coupon_select: 84,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 3,
        event_id: 9,
      },
      {
        coupon_select: 51,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 4,
        event_id: 1,
      },
      {
        coupon_select: 1,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 4,
        event_id: 2,
      },
      {
        coupon_select: 11,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 4,
        event_id: 3,
      },
      {
        coupon_select: 21,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 4,
        event_id: 4,
      },
      {
        coupon_select: 31,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 4,
        event_id: 5,
      },
      {
        coupon_select: 42,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 4,
        event_id: 6,
      },
      {
        coupon_select: 64,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 4,
        event_id: 7,
      },
      {
        coupon_select: 71,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 4,
        event_id: 8,
      },
      {
        coupon_select: 82,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 4,
        event_id: 9,
      },
      {
        coupon_select: 52,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 5,
        event_id: 1,
      },
      {
        coupon_select: 2,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 5,
        event_id: 2,
      },
      {
        coupon_select: 12,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 5,
        event_id: 3,
      },
      {
        coupon_select: 22,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 5,
        event_id: 4,
      },
      {
        coupon_select: 32,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 5,
        event_id: 5,
      },
      {
        coupon_select: 42,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 5,
        event_id: 6,
      },
      {
        coupon_select: 65,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 5,
        event_id: 7,
      },
      {
        coupon_select: 72,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 5,
        event_id: 8,
      },
      {
        coupon_select: 84,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 5,
        event_id: 9,
      },
      {
        coupon_select: 52,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 6,
        event_id: 1,
      },
      {
        coupon_select: 2,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 6,
        event_id: 2,
      },
      {
        coupon_select: 12,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 6,
        event_id: 3,
      },
      {
        coupon_select: 22,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 6,
        event_id: 4,
      },
      {
        coupon_select: 32,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 6,
        event_id: 5,
      },
      {
        coupon_select: 42,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 6,
        event_id: 6,
      },
      {
        coupon_select: 65,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 6,
        event_id: 7,
      },
      {
        coupon_select: 72,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 6,
        event_id: 8,
      },
      {
        coupon_select: 84,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 6,
        event_id: 9,
      },
      {
        coupon_select: 51,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 7,
        event_id: 1,
      },
      {
        coupon_select: 2,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 7,
        event_id: 2,
      },
      {
        coupon_select: 11,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 7,
        event_id: 3,
      },
      {
        coupon_select: 22,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 7,
        event_id: 4,
      },
      {
        coupon_select: 31,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 7,
        event_id: 5,
      },
      {
        coupon_select: 41,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 7,
        event_id: 6,
      },
      {
        coupon_select: 64,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 7,
        event_id: 7,
      },
      {
        coupon_select: 71,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 7,
        event_id: 8,
      },
      {
        coupon_select: 82,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 7,
        event_id: 9,
      },
      {
        coupon_select: 52,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 8,
        event_id: 1,
      },
      {
        coupon_select: 2,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 8,
        event_id: 2,
      },
      {
        coupon_select: 12,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 8,
        event_id: 3,
      },
      {
        coupon_select: 21,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 8,
        event_id: 4,
      },
      {
        coupon_select: 31,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 8,
        event_id: 5,
      },
      {
        coupon_select: 41,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 8,
        event_id: 6,
      },
      {
        coupon_select: 64,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 8,
        event_id: 7,
      },
      {
        coupon_select: 71,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 8,
        event_id: 8,
      },
      {
        coupon_select: 82,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 8,
        event_id: 9,
      },
      {
        coupon_select: 51,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 9,
        event_id: 1,
      },
      {
        coupon_select: 1,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 9,
        event_id: 2,
      },
      {
        coupon_select: 11,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 9,
        event_id: 3,
      },
      {
        coupon_select: 22,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 9,
        event_id: 4,
      },
      {
        coupon_select: 32,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 9,
        event_id: 5,
      },
      {
        coupon_select: 42,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 9,
        event_id: 6,
      },
      {
        coupon_select: 65,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 9,
        event_id: 7,
      },
      {
        coupon_select: 72,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 9,
        event_id: 8,
      },
      {
        coupon_select: 84,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 9,
        event_id: 9,
      },
      {
        coupon_select: 51,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 10,
        event_id: 1,
      },
      {
        coupon_select: 2,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 10,
        event_id: 2,
      },
      {
        coupon_select: 12,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 10,
        event_id: 3,
      },
      {
        coupon_select: 22,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 10,
        event_id: 4,
      },
      {
        coupon_select: 32,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 10,
        event_id: 5,
      },
      {
        coupon_select: 42,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 10,
        event_id: 6,
      },
      {
        coupon_select: 65,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 10,
        event_id: 7,
      },
      {
        coupon_select: 72,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 10,
        event_id: 8,
      },
      {
        coupon_select: 84,
        coupon_use: false,
        coupon_date: new Date(),
        user_id: 10,
        event_id: 9,
      },
    ];

    return queryInterface.bulkInsert("coupons", datas, {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("coupons", null, {});
  },
};
